radius = float(input('Provide radius value:'))
pi = float(3.14)
area = float(pi * (radius**2))
circumfrence = float(pi * radius * 2)
print (str(area) + ' squared units')
print (str(circumfrence) + ' units')
