shares_purchased = shares_sold = int(2000)
share_cost = float(40.00)
share_value = float(42.75)
share_value_total = float(shares_sold * share_value)
brocker_sold_profit = float(shares_sold * share_value * .03)
print (str(shares_purchased * share_cost) + '$ = paid for stock')
print (str(shares_purchased * share_cost * .03) + '$ = paid to brocker after purchase of stock')
print (str(share_value_total) + '$ = amount stock sold for')
print (str(brocker_sold_profit) + '$ = paid to brocker after sold stock')
print (str(share_value_total - brocker_sold_profit) + '$ = Joes profit')
